Vagrant.configure("2") do |config|
  
    config.vm.define "centosVM1" do |vm1|
        vm1.vm.box = "centos/7"
    end
  
    config.vm.define "centosVM2" do |vm2|
        vm2.vm.box = "centos/7"
    end
end