Vagrant.configure("2") do |config|
    config.vm.boot_timeout = 1200

    config.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
        vb.default_nic_type = "82540EM"
        vb.cpus = 1
    end

    config.vm.define "centosvm1" do |vm1|
        vm1.vm.box =  "generic/centos7"
    end
  
    config.vm.define "centosvm2" do |vm2|
        vm2.vm.box =  "generic/centos7"
    end
end